- name: add jenkins apt key
  apt_key: data="{{ lookup('file', 'jenkins.io.aptKey') }}" state=present
  register: jenkinskey

- name: add jenkins repo
  apt_repository: repo='deb http://pkg.jenkins.io/debian-stable binary/' state=present
  register: jenkinsrepo

- name: install jenkins
  apt: name=jenkins update_cache="{{ (jenkinsrepo.changed or jenkinskey.changed) | ternary('yes', 'no') }}"

- name: enable and start jenkins service
  service: name=jenkins state=started enabled=yes
